#!/usr/bin/env lua

function go(inpath, outpath, symbol)
    local inf = assert(io.open(inpath, "rb"))
    -- Skip until we see a line ending in "by:"
    local l
    repeat
        l = inf:read()
    until l:match("by:$")
    inf:read() -- skip the next line too
    local outf = assert(io.open(outpath,"wb"))
    outf:write[[
// Automatically generated by A1-AUTHORS-update.lua
// Do not edit manually!

]]
    for l in inf:lines() do
        if l:match("[\x80-\xFF]") then
            outf:write(("%s.push_back(utf8_to_mac_roman(%q));\n"):format(symbol, l))
        else
            outf:write(("%s.push_back(%q);\n"):format(symbol, l))
        end
    end
    outf:close()
end

go("A1-AUTHORS", "Source_Files/Misc/a1-authors.h", "a1_authors")
go("AB-AUTHORS", "Source_Files/Misc/ab-authors.h", "ab_authors")
