#!/usr/bin/env bash

set -e
cd "$(dirname $0)"

if ! which inkscape &>/dev/null; then
    echo "This script requires Inkscape to be installed and in your PATH."
    exit 1
fi

if ! which convert &>/dev/null; then
    echo "This script requires ImageMagick (i.e. convert) to be installed and in your PATH."
    exit 1
fi

if ! which lua &>/dev/null; then
    echo "This script requires Lua to be installed and in your PATH."
    exit 1
fi

function out() {
    inkscape --export-type="png" "$1".svg
    convert "$1".png "$1".bmp
    cat > ../Source_Files/Misc/"$1".h <<EOF
// Automatically generated by the "data/powered_by_alephbet.sh" script.
EOF
    lua bin2h.lua "$1"_bmp < "$1".bmp >> ../Source_Files/Misc/"$1".h
}

out powered_by_alephbet
out powered_by_alephbet_h
